### ISSUE TITLE
Module not found 

### ISSUE THREAD

**Issue by Lenos500** [YeZiyi1998/Brain-language-generation#1]
Traceback (most recent call last):
  File "/content/Brain-language-generation/language_generation/src/model.py", line 13, in <module>
    from settings import model_name2path, model2hidden
ModuleNotFoundError: No module named 'settings'
 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Brain-language-generation/language_generation/src/main.py", line 8, in <module>
    from model import Decoding_model 
  File "/content/Brain-language-generation/language_generation/src/model.py", line 18, in <module>
    from src.settings import model_name2path, model2hidden
ModuleNotFoundError: No module named 'src'

**Comment by YeZiyi1998** [comment]
Thanks for your issue, a recent update changed the file "settings.py" to "settings_template.py", please modify "settings_template.py" according to your setting and rename it as "settings.py".
